name: Build and deploy ASP.Net Core app to Azure Web App - hereismilo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        # We move into the folder AND build in one step to avoid path errors
        run: |
          cd portfolio/portfolio
          dotnet build --configuration Release

      - name: dotnet publish
        # We move into the folder AND publish
        run: |
          cd portfolio/portfolio
          dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish # Keep this simple
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B3FE3A1758344B34B242549218D487E7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_131929EEA80742359D0EC58D9F5EDAF3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B3C143A13C94697B5E09C46A8851B3D }}
      
      - name: Build with dotnet
        run: |
          dotnet build --configuration Release
      
      - name: dotnet publish
        run: |
          dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
